package org.example.attendTrack.attendance;

/**
 * Where an attendance record originated. Replaces the fragile
 * {@code manualOverride && manager == null} heuristic that could not tell a
 * scheduler auto-checkout apart from an operator's manual confirmation at the terminal.
 */
public enum AttendanceSource {
    /** Face recognition confirmed at the verify terminal. */
    TERMINAL_FACE,
    /** Manual confirmation at the verify terminal (operator picked the worker from the list). */
    TERMINAL_MANUAL,
    /** Entered manually by an admin from the dashboard. */
    ADMIN_MANUAL,
    /** Generated by the automatic end-of-day checkout scheduler. */
    SCHEDULER_AUTO
}
