package org.example.attendTrack.report.dto;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.UUID;

/**
 * One row in the "by-site" worked hours report.
 *
 * pairIndex ≥ 0 → session row (one CHECK_IN / CHECK_OUT pair within the day).
 * pairIndex == -1 → day-total row, emitted only when there are ≥ 2 sessions on the same day.
 *   Total rows have checkIn/checkOut = null and carry the day-level correction fields.
 *
 * checkOut and calculatedHours are null when the shift is still open (no CHECK_OUT recorded).
 * inferredCheckOut is true when checkOut was not recorded directly but was inferred from
 *   the worker's next CHECK_IN at a different site on the same day (multi-site auto-close).
 * autoCheckout is true when the checkout record has manualOverride=true (auto-generated by
 *   the scheduler, or manually confirmed by a manager at the verify terminal).
 * correctedHours and correctionNote are null when no manual correction exists.
 * effectiveHours is set only on single-session rows and day-total rows; null on session rows
 *   that belong to a multi-session day (prevents double-counting in summary totals).
 * checkInLat/checkInLng are null when the check-in record was created manually (0,0 coords)
 *   or on day-total rows. Otherwise set from the real CHECK_IN attendance record.
 * checkOutLat/checkOutLng are null for open shifts, inferred checkouts, and day-total rows —
 *   only set when a real CHECK_OUT attendance record exists with non-zero coordinates.
 */
public record WorkedHoursRow(
        UUID checkInId,            // null on day-total rows and inferred-checkout rows without a real record
        UUID checkOutId,           // null on open shifts, inferred checkouts, and day-total rows
        UUID workerId,
        String workerName,
        String companyName,
        UUID siteId,
        String siteName,
        LocalDate date,
        int pairIndex,             // ≥0 = session index; -1 = day-total row
        LocalTime checkIn,
        LocalTime checkOut,        // null → open shift or day-total row
        boolean inferredCheckOut,
        boolean autoCheckout,
        Double calculatedHours,    // this session's hours (or day sum on total row); null → open shift
        Double effectiveHours,     // corrected or calculated total; null on multi-session session rows
        Double correctedHours,     // null → no correction
        String correctionNote,     // null → no correction
        Double checkOutLat,        // null → open shift, inferred checkout, or day-total row
        Double checkOutLng,        // null → same cases as checkOutLat
        Double checkInLat,         // null → manual record (0,0 coords) or day-total row
        Double checkInLng          // null → same cases as checkInLat
) {}
